name: Build no-phi-ai golang app binary

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup golang
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Use make to build the binary
      run: make build

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: no-phi-ai
        path: build/no-phi-ai
          
